---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: whoami
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          cpu: 1
          memory: 10Mi
        controlledResources: ["cpu", "memory"]
